//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcCompleto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolABC
    {
        public RolABC()
        {
            this.EmpleadoABC = new HashSet<EmpleadoABC>();
        }
    
        public int idrol { get; set; }
        public string desc_rol { get; set; }
    
        public virtual ICollection<EmpleadoABC> EmpleadoABC { get; set; }
    }
}
