//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcCompleto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarioABC
    {
        public int idNumEmpleado { get; set; }
        public Nullable<double> salario_mensual { get; set; }
    
        public virtual EmpleadoABC EmpleadoABC { get; set; }
    }
}
