//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcCompleto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoABC
    {
        public TipoABC()
        {
            this.EmpleadoABC = new HashSet<EmpleadoABC>();
        }
    
        public int idtipo { get; set; }
        public string desc_tipo { get; set; }
    
        public virtual ICollection<EmpleadoABC> EmpleadoABC { get; set; }
    }
}
